name: Build AtherAuth Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: AtherAuth-Plugin
        path: target/AtherAuth-*.jar
